from prompt_training.prompts import (
    BLAKE_SPEAK,
    COUNCIL_DECIDE,
    COUNCIL_FRAME,
    DELTA_FINAL_SYSTEM,
    KIERKEGAARD_REFLECT,
    KIERKEGAARD_SPEAK,
    LAMBDA_REFLECT,
    MORRISON_SPEAK,
    PSI_REFLECT,
)

__all__ = [
    "BLAKE_SPEAK",
    "COUNCIL_DECIDE",
    "COUNCIL_FRAME",
    "DELTA_FINAL_SYSTEM",
    "KIERKEGAARD_REFLECT",
    "KIERKEGAARD_SPEAK",
    "LAMBDA_REFLECT",
    "MORRISON_SPEAK",
    "PSI_REFLECT",
]
